### ISSUE TITLE
Preparation for deployment

### ISSUE THREAD

**Issue by cc-wong** [cc-wong/react-demo#13]
**To-do list (TBC):**
- [x] Make changes/additions necessary for creating a production build.
- [x] Prepare a cloud environment to deploy to (Netlify?)
- [x] Revise the way of communication on Render instance spin-down and keep-alive mechanism by UptimeRobot.
~~- [ ] Move API call logic to separate module.~~ (not as simple as it seems)
- [x] Revise README page: Revise headings and wordings.
- [x] Revise README page: Call attention to API instance information in the Wiki
- [x] Upate Wiki.
- [x] Update version to 1.0.0.
- [x] Research and implement build hook for Netlify.
- [x] Check free instance hours quota used for keep-alive only.
- [x] Add remark on UptimeRobot keep-alive mechanism in [`python-webservice-demo`](https://github.com/cc-wong/python-webservice-demo) Wiki.
- [x] Update Wiki: Netlify deployment workflow and its YAML in the project structure.

**Pre-requisite(s)**
- [x] [Make changes to take environment variables on startup](https://github.com/cc-wong/react-demo/issues/16)

Environments to deploy to:
1. Netlify
    - DONE
2. ~~GitHub Pages of `react-demo`~~

**Comment by cc-wong** [comment]
Deployed to Netlify.

**URL:** https://honbasho-schedule-lookup.netlify.app/
![Image](https://github.com/cc-wong/react-demo/assets/52849782/6858f88c-312a-469c-8e54-bf79412fb60e)

**Comment by cc-wong** [comment]
Regarding the API service:
* Tried deploying the webservice on Azure. Was able to get one instance up and running, but it goes to sleep after being idle for 20 minutes. Startup time after that was worse than Render (more than 1 minute!).
* Found a keepalive cloud service [UptimeRobot](https://uptimerobot.com/). Testing its free tier on the Render instance.

**Comment by cc-wong** [comment]
Render provides a healthcheck mechanism, but it _does not_ prevent service spin-down.

<https://community.render.com/t/does-starter-instance-type-have-24-7-site-uptime/10166>

An external solution is still needed for keep-alive.

**Comment by cc-wong** [comment]
> Regarding the API service:
>     * Tried deploying the webservice on Azure. Was able to get one instance up and running, but it goes to sleep after being idle for 20 minutes. Startup time after that was worse than Render (more than 1 minute!).
>     * Found a keepalive cloud service [UptimeRobot](https://uptimerobot.com/). Testing its free tier on the Render instance.

Added `/healthcheck` endpoint to API webservice. Using UptimeRobot with this endpoint to ping every 5 minutes worked overnight.

**Comment by cc-wong** [comment]
> Added `/healthcheck` endpoint to API webservice. Using UptimeRobot with this endpoint to ping every 5 minutes overnight worked. 
>     * Try pinging for every 10 minutes. ~(Did not work with the original default endpoint.)~ [UPDATE] Worked.

### Does the free tier for Render have enough free instance hours to use the keepalive mechanism?

**Accumulated free instance hours used:-**
April 4 5:25pm: 34.9 hours 
April 5 5:25pm: ? hours

**Total quota used:** ? hours

**Comment by cc-wong** [comment]
Set up GitHub workflow to deploy to Netlify on push to `master` only.

**Commits:**
* f95c7428a71f5340ffc95a2a61e721833aa7b323
* e4e1720f0ab1c36b8ada1945123f7e39eb65cc46
* a0153e752c517dd0d6657fb308238d74f10201da
* 26b3fe15a90b18460d53a7643ac6172461f305fd
* ffc2e30437e531bc53dfa2be3dfa17afb7ac74ba
* b9e46b613dda1ba1fd61a36821a16013cce9c8da

**Comment by cc-wong** [comment]
[Release v1.0.0](https://github.com/cc-wong/react-demo/releases/tag/v1.0.0) created.
